### ISSUE TITLE
Bedfile standarization

### ISSUE THREAD

**Issue by jguinney** [Sage-Bionetworks/Genie#10]
Groups are not defining panel definitions in a consistent format. Need gene panel SOPs.

**Comment by thomasyu888** [comment]
Omitting DFCI and VICC for now.

**Comment by thomasyu888** [comment]
Compiled: https://www.synapse.org/#!Synapse:syn7444851

**Comment by kkdang** [comment]
Add exonic/intronic/intergenic to each BED file entry
