### ISSUE TITLE
_get_dataframe in clinical not used

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Genie#104]
https://github.com/Sage-Bionetworks/Genie/blob/master/genie/clinical.py#L497

Was a bit confused, because `example_filetype_format.py` shows that this is used by the `read_file`. This class doesn't follow that pattern, and it's own `_get_dataframe` function is never called.

**Comment by thomasyu888** [comment]
read_file is by default called by `validate` and `process`: https://github.com/Sage-Bionetworks/Genie/blob/develop/genie/example_filetype_format.py#L91, https://github.com/Sage-Bionetworks/Genie/blob/develop/genie/example_filetype_format.py#L112.

Each `read_file` called the `_get_dataframe`: https://github.com/Sage-Bionetworks/Genie/blob/develop/genie/example_filetype_format.py#L20

The clinical file just has a different `_get_dataframe`

**Comment by kdaily** [comment]
In `process_steps` it's not used though?

https://github.com/Sage-Bionetworks/Genie/blob/master/genie/clinical.py#L201

**Comment by thomasyu888** [comment]
Ah. That is done intentionally: https://github.com/Sage-Bionetworks/Genie/blob/develop/genie/example_filetype_format.py#L111

I parse out information from the filepath (which I should do in the preprocess)
```
        if "patient" in filePath.lower():
            clinicalTemplate = pd.DataFrame(columns=patientCols)
            patient = True
        elif "sample" in filePath.lower():
            clinicalTemplate = pd.DataFrame(columns=sampleCols)
            sample = True
```

**Comment by kdaily** [comment]
Thanks! Yeah was about to post that line that restricts the files read - another place that I have to register my new formats. Is there an issue to track this? seems like a simple change that I could implement.

**Comment by thomasyu888** [comment]
I made edits to my original post.  I will track the issue using this.  Unfortunately, I will have to run the integration test locally prior to pulling in any of your changes.
