### ISSUE TITLE
Add parameters to __init__

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/Genie#105]
* oncotree url
* file path list
* testing / staging

**Comment by kdaily** [comment]
Disagree adding testing/staging. This should just use the proposed config file approach.

File path list makes sense if you propose to use a single validator for a single file. If you ever want to reuse a validator to validate multiple files of the same type, then it wouldn't be part of the init. Then some other class methods could become static methods.

**Comment by thomasyu888** [comment]
Clinical validation has to happen across the two files. Most of the code validates one file at a time. I think the only place that actually needs it as a list is the clinical file.  Making a change from list -> not list would be non trivial.

**Comment by kdaily** [comment]
I meant 'single instance of a validator for a single submitted file or files'.

**Comment by thomasyu888** [comment]
#88
