### ISSUE TITLE
Instantiate classes

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/Genie#106]
```
PROCESS_FILES[fileType](syn, center, threads).validateFilename(filePath)
```

should be

```
validator = PROCESS_FILES[fileType](syn, center, threads)
validator.validateFilename(...)
```

**Comment by kdaily** [comment]
Or, depending on the philosophy:

`validator = PROCESS_FILES[fileType](syn, center, filePath, threads)`

**Comment by thomasyu888** [comment]
View #105. There are many more I could potentially add.  Also `threads` isn't used anywhere.
