### ISSUE TITLE
cna does syn.store, blocking removal of newPath

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Genie#179]
Need to move that step - it doesn't follow the pattern of the rest.

**Comment by thomasyu888** [comment]
Ah. This is one of those genie issues where the CNA file is processed and uploaded into a folder and not into a database because there are too many columns for a synapse table to handle

**Comment by kdaily** [comment]
which is fine, but breaks the contract of what `_process` does almost everywhere else.

**Comment by thomasyu888** [comment]
Ideally the upload part happens outside of _process. That's the real refactor I want to make but vcfs are a bother right this moment.

**Comment by thomasyu888** [comment]
Won't do.
