### ISSUE TITLE
use file type, not file name extension, if filtering of files is needed

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Genie#196]
Functions in `input_to_database` currently check for a file extension (like `.vcf`) when deciding what to validate and process. This means that even if a user writes a different class to represent vcf files, it will probably get filtered due to the default logic based on GENIE's specific VCF issues.

Instead of using the file extension, it should check the files `fileType` based on registered `FileTypeFormat` classes.

**Comment by thomasyu888** [comment]
#249
