### ISSUE TITLE
tests shouldn't use specific genie classes

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Genie#225]
In working towards making Genie more general, the test suite shouldn't depend on specific file type classes to run the tests (like `genie.clinical.clinical`). It should use 'test' classes that have the right interface just to test the functionality of Genie validation, processing, and database update operations. Anything that is specific to testing any one of the file type classes should be separated.

See https://github.com/veo-ibd/Genie/commit/8a04a3b6a6a502bbeb1b4a4bdaf3e4741fde028b#diff-7488fbee800ac1a3edef38842281bda6R105 and https://github.com/veo-ibd/Genie/commit/8a04a3b6a6a502bbeb1b4a4bdaf3e4741fde028b#diff-7488fbee800ac1a3edef38842281bda6R14 as examples of how this can be done (either define a sub-class in the test suite, or overload the base class).

**Comment by thomasyu888** [comment]
Thanks Kenny,  this is mainly because of the special cases we have in GENIE
* vcf
* clinical

Once those are separated, in a separate repository, I can go ahead with this fix.
