### ISSUE TITLE
PHI cutoff should be greater or equal to 90 years in days

### ISSUE THREAD

**Issue by xindiguo** [Sage-Bionetworks/Genie#283]
The interval cutoff should be >= math.floor(90*365.24)

https://github.com/Sage-Bionetworks/Genie/blob/cfa33533026cb09d7d56616ebc516942a9415bcb/genie/database_to_staging.py#L105

**Comment by thomasyu888** [comment]
The BPC redaction policy should match the GENIE one.  redact 89 years by days.
