### ISSUE TITLE
UHN vcf2maf

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/Genie#34]
```
vcf2maf.pl --input-vcf ... --input-maf ... --tumor-id sample_id --normal-id normal --vcf-tumor-id sample_id
```
For some reason the UHN mutation file's `Tumor_Sample_Barcode` is still being annotated with the vcf file name without the `.vcf`.   However, the `--tumor-id` is supposed to annotate the maf file with the correct annotation.  Need to double check if it works.

**Comment by thomasyu888** [comment]
Small error in code that I fixed.

**Comment by ckandoth** [comment]
@thomasyu888 Is this something I need to fix in the main vcf2maf repo too?

**Comment by thomasyu888** [comment]
No.  This is an error that was in my code.  Not in the vcf2maf repo.  Thanks for following up
