### ISSUE TITLE
remove samples not marked 'keep' in variant merge list

### ISSUE THREAD

**Issue by kkdang** [Sage-Bionetworks/Genie#37]
Groups that want to keep variants will submit new mutation files.

**Comment by thomasyu888** [comment]
There are still a list of samples that are not annotated.  All samples that are marked as TOSS or blank will be thrown out.

**Comment by carlvirtanen** [comment]
Can somebody respond to us at UHN to explain this? the title of this thread and comments we can't figure out and whether this affects us...

**Comment by ahmetz** [comment]
All MSK mutations were reviewed and mutations that need to be merged are merged. They all can be considered 'keep'

**Comment by carlvirtanen** [comment]
Sorry still not clear as im at uhn

**Comment by thomasyu888** [comment]
We will let you know as soon as possible.  There are still a few things that we are trying to figure out on our end.  Thank you for your patience.

**Comment by carlvirtanen** [comment]
Ok thanks!

**Comment by kkdang** [comment]
@carlvirtanen: The process is more clearly documented here:
https://basecamp.com/2995369/projects/12642638/messages/64535564

Take a look and post to basecamp if you have questions.
