### ISSUE TITLE
add maf validation check for NA in Tumor_seq_allele columns

### ISSUE THREAD

**Issue by kkdang** [Sage-Bionetworks/Genie#49]
Check for 'NA' in tumor_seq_allele and tumor_seq_allele2. If found, issue very noticeable warning that this will be interpreted as a valid allele and if really an 'na' it should be removed from input. We can't purge these automatically because NA as nucleotide codes is a possible allele.

**Comment by ckandoth** [comment]
Thanks @kkdang. Also need a check for the ref_allele. An "N" is used to pad regions of GRCh37, so it will show up in the sequence of long deletions that cross into introns or intergenic regions. We shouldn't encounter too many in Genie long-term, but it would be unsafe to hardcode a removal of anything that's "NA". So good call on putting this in the validator, not the workflow.
